name: update-dotnet-sdk

on:
  schedule:
    - cron:  '0 12 * * WED'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-dotnet-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@b5684309b4d6dd59ee955b150f5632c5f3a59f79 # v3.1.4
    with:
      labels: "dependencies,.NET"
      update-nuget-packages: false
      user-email: '138034000+polly-updater-bot[bot]@users.noreply.github.com'
      user-name: 'polly-updater-bot[bot]'
    secrets:
      application-id: ${{ secrets.POLLY_UPDATER_BOT_APP_ID }}
      application-private-key: ${{ secrets.POLLY_UPDATER_BOT_KEY }}

  add-security-label:
    needs: update-dotnet-sdk
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if : |
      needs.update-dotnet-sdk.outputs.sdk-updated =='true' &&
      needs.update-dotnet-sdk.outputs.security == 'true'
    steps:
    - name: Add security label
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr edit "${{ needs.update-dotnet-sdk.outputs.pull-request-html-url }}" --add-label security
